name: Create Tag
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
      - 'create-tag.yml'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE.md'
      - 'README.md'
      - '.github/**'
      - 'examples/**'
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ env.VERSION }}"
          GITHUB_TOKEN: "${{ secrets.TOKEN_GITHUB }}"
